### ISSUE TITLE
EL10 support checklist

### ISSUE THREAD

**Issue by achilleas-k** [osbuild/images#518]
RHEL 10.0 and CentOS Stream 10 support was added and tested in #516.  Certain image types and features were not added (or tested) because of missing packages.

Image types:
- [x] ec2
    - #529
- [x] gce
    - #869
- [x] rhui variants
    - Azure: #1067
- [x] ~~edge: firmware packages~~ (No Edge in RHEL 10)
- [x] image-installer: firmware packages
    - #869

Customziations:
- [x] openscap: missing package `scap-security-guide`
    - #924

**Comment by achilleas-k** [comment]
Assigned to you since you did most of the work :)
